### PR TITLE
add functionality for 'New Consignment CSV Import File Format'

### PR DESCRIPTION
**Pull request by posttechguy**
Australia Post have updated to a new csv Consignment import format.

### CODE REVIEW

**Comment by chnorton** [comment]
Thanks for submitting this - I'll take a look at it and provide an update next week.

**Comment by chnorton** [comment]
@posttechguy Do you have a reference for the new import format?

**Comment by posttechguy** [comment]
@chnorton Here is the link to the sample that I was given from AustPost

https://docs.google.com/spreadsheets/d/1uZui9fFVmiITZt7xNXy9PBvmLLtAi-CeXdP8UAqD8FA/edit?usp=sharing

Bevan

**Comment by posttechguy** [comment]
Hi Chris,
What is happening with this PR?
Bevan

**Comment by posttechguy** [comment]
Hi @chnorton,
What is happening with this PR?
Bevan

**Comment by chnorton** [comment]
@posttechguy Sorry for the delay on getting to this one. I've made some style changes - mostly just converting the header strings into arrays, since they ended up being exploded anyway. Let me know if you run into any issues with this, and thanks again for submitting the code!

**Comment by posttechguy** [comment]
@chnorton, Thanks for that. The code changes were fine. I may have some more soon, speaking with EParcel and the definition of international parcels.

**Pull request closed without merging**
